Repository thumbtack-turing/thumbtack_ui, pull requests merged in 2021-12, with the labels that each got.

#14 Create pull_request_template.md
  docs/pull_request_template.md
Labels: FE, setup

#15 Feature/setup apollo
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/client/cache.tsx
  src/client/client.tsx
  src/components/About.tsx
  src/components/App.tsx
  src/components/Creators.tsx
  src/components/Folder.tsx
  src/components/Header.tsx
  src/components/LandingPage.tsx
  src/components/Logo.tsx
  src/components/Main.tsx
  src/components/Menu.tsx
  src/components/Profile.tsx
  src/components/Resource.tsx
  src/components/ResourceForm.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/models/todo.tsx
  src/operations/queries/getAllTodos.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/base/_mixins.scss
  src/styles/base/_typography.scss
  src/styles/base/_variables.scss
  src/styles/index.scss
  src/styles/layouts/_App.scss
  src/styles/layouts/_base-layout.scss
  src/styles/utilities/_normalize.scss
  src/styles/utilities/_reset.scss
  src/styles/utilities/_responsive.scss
Labels: FE, setup

#16 Circleci project setup
  .circleci/config.yml
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/integration/test.spec.js
Labels: FE, setup

#17 Feature/profile page
  .circleci/config.yml
  cypress/integration/profile.spec.js
  cypress/integration/test.spec.js
  cypress/utils/graphql-test-utils.js
  package-lock.json
  package.json
  src/assets/PinClipart.com_caliper-clipart_1117848.png
  src/assets/cat_rainbow.gif
  src/assets/medium-blue-folder-hi.png
  src/client/cache.tsx
  src/client/client.tsx
  src/components/AddForm.tsx
  src/components/App.tsx
  src/components/BaseFolderView.tsx
  src/components/CreateFolder.tsx
  src/components/CreateResource.tsx
  src/components/Error.tsx
  src/components/Folder.tsx
  src/components/Header.tsx
  src/components/LandingPage.tsx
  src/components/Loading.tsx
  src/components/Main.tsx
  src/components/Profile.tsx
  src/components/Resource.tsx
  src/components/ResourceForm.tsx
  src/components/SubFolderView.tsx
  src/index.tsx
  src/models/Folder.tsx
  src/models/Gallery.tsx
  src/models/Resource.tsx
  src/models/User.tsx
  src/models/todo.tsx
  src/operations/mutations/CREATE_FOLDER.tsx
  src/operations/mutations/CREATE_RESOURCE.tsx
  src/operations/mutations/CREATE_USER.tsx
  src/operations/mutations/DELETE_FOLDER.tsx
  src/operations/mutations/DELETE_RESOURCE.tsx
  src/operations/mutations/DELETE_USER.tsx
  src/operations/mutations/UPDATE_FOLDER.tsx
  src/operations/mutations/UPDATE_RESOURCE.tsx
  src/operations/queries/GET_FOLDER.tsx
  src/operations/queries/GET_USER.tsx
  src/operations/queries/getAllTodos.tsx
  src/operations/read/GET_CURRENT_FOLDER.tsx
  src/operations/read/READ_PARENT_ID.tsx
  src/styles/base/_mixins.scss
  src/styles/base/_palettes.scss
  src/styles/base/_themes.scss
  src/styles/base/_typography.scss
  src/styles/index.scss
  src/styles/layouts/_App.scss
  src/styles/layouts/_Gallery.scss
  src/styles/layouts/_Header.scss
  src/styles/layouts/_Profile.scss
  src/styles/layouts/_base-layout.scss
  src/styles/modules/_AddForm.scss
  src/styles/modules/_Folder.scss
  src/styles/modules/_Loading.scss
  src/styles/modules/_Resource.scss
  src/styles/utilities/_reset.scss
Labels: enhancement, FE, testing

#19 Feature/delete resource or folder
  cypress/integration/profile.spec.js
  src/assets/button-close-icon-645944.png
  src/components/BaseFolderView.tsx
  src/components/Folder.tsx
  src/components/Profile.tsx
  src/components/Resource.tsx
  src/components/SubFolderView.tsx
  src/operations/mutations/DELETE_FOLDER.tsx
  src/operations/mutations/DELETE_RESOURCE.tsx
  src/styles/layouts/_Gallery.scss
  src/styles/layouts/_Profile.scss
  src/styles/modules/_AddForm.scss
  src/styles/modules/_Folder.scss
  src/styles/modules/_Resource.scss
Labels: enhancement, FE, testing

#24 Feature/resource styling
  cypress/integration/drag.spec.js
  package-lock.json
  src/assets/edit.png
  src/assets/move-up.png
  src/assets/move.png
  src/assets/trash.png
  src/components/CreateFolder.tsx
  src/components/Folder.tsx
  src/components/Resource.tsx
  src/constants/ItemTypes.tsx
  src/operations/mutations/UPDATE_FOLDER.tsx
  src/styles/modules/_Folder.scss
  src/styles/modules/_Resource.scss
Labels: enhancement

#26 Feature/resource text
  src/assets/button-close-icon-645944.png
  src/assets/clear-all.svg
  src/assets/edit.png
  src/assets/folder2.png
  src/assets/move-up.png
  src/assets/pass.svg
  src/assets/trash.png
  src/components/Folder.tsx
  src/components/FolderTextEditor.tsx
  src/components/Resource.tsx
  src/components/ResourceTextEditor.tsx
  src/operations/mutations/UPDATE_FOLDER.tsx
  src/operations/mutations/UPDATE_RESOURCE.tsx
  src/react-app-env.d.ts
  src/styles/index.scss
  src/styles/layouts/_Gallery.scss
  src/styles/modules/_Folder.scss
  src/styles/modules/_TextEditor.scss
Labels: enhancement, FE

#27 Feature/resource text
  src/assets/apple.png
  src/assets/google.png
  src/components/Footer.tsx
  src/components/LandingPage.tsx
  src/react-app-env.d.ts
  src/styles/index.scss
  src/styles/layouts/_Footer.scss
  src/styles/layouts/_Gallery.scss
  src/styles/layouts/_LandingBlock1.scss
  src/styles/modules/_Folder.scss
  src/styles/modules/_LightDarkModeToggle.scss
Labels: enhancement, FE

#29 Style/unify profile
  public/favicon.ico
  src/assets/folder-up.png
  src/assets/loading-wheel.gif
  src/assets/trashcan.png
  src/client/cache.tsx
  src/components/App.tsx
  src/components/BaseFolderView.tsx
  src/components/CreateFolder.tsx
  src/components/CreateResource.tsx
  src/components/Error.tsx
  src/components/Folder.tsx
  src/components/FolderTextEditor.tsx
  src/components/FooterRelocateOrDelete.tsx
  src/components/FourOhFour.tsx
  src/components/LightDarkModeToggle.tsx
  src/components/Loading.tsx
  src/components/Main.tsx
  src/components/Profile.tsx
  src/components/Relocate.tsx
  src/components/Resource.tsx
  src/components/ResourceTextEditor.tsx
  src/components/SubFolderView.tsx
  src/components/TrashCan.tsx
  src/index.tsx
  src/operations/queries/GET_FOLDER.tsx
  src/operations/queries/GET_USER.tsx
  src/styles/base/_palettes.scss
  src/styles/base/_themes.scss
  src/styles/base/_typography.scss
  src/styles/index.scss
  src/styles/layouts/_Footer.scss
  src/styles/layouts/_Gallery.scss
  src/styles/modules/_Folder.scss
  src/styles/modules/_FourOhFour.scss
  src/styles/modules/_Loading.scss
  src/styles/modules/_Resource.scss
  src/styles/modules/_TextEditor.scss
  src/utilities/folderContainsInfo.tsx
Labels: enhancement, FE, styling

#31 Make adjustments to pass existing tests
  cypress/integration/profile.spec.js
  src/components/Resource.tsx
Labels: FE, testing
